= Developing Restful APIs: A Comprehensive Set of Guidelines
////
https://travis-ci.org/zalando/restful-api-guidelines[image:https://travis-ci.org/zalando/restful-api-guidelines.svg?branch=master[Build Status]]
Latest published version:
http://zalando.github.io/restful-api-guidelines/[*HTML*],
http://zalando.github.io/restful-api-guidelines/restful-api-guidelines.pdf[*PDF*],
http://zalando.github.io/restful-api-guidelines/restful-api-guidelines.epub[*EPUB3*]
////

*This work is a fork of https://github.com/zalando/restful-api-guidelines[Developing Restful APIs: A Comprehensive Set of Guidelines by Zalando] by Zalando, licensed under CC BY (Creative commons Attribution 4.0).*

== Purpose

Great RESTful APIs look like they were designed by a single team. This
promotes API adoption, reduces friction, and enables clients to use them
properly. This comprehensive set of guidelines helps to build APIs that meet
this standard, and to answer many common questions encountered along the
way of RESTful API development.

== Usage

Feel free to use these guidelines as a guidance for your own
development. Note that we encourage our own teams to use them in order
to challenge their APIs. As such, you should consider this to be a
living, evolving document. We will revise and update based on our
learnings and experiences.

See link:BUILD.adoc[BUILD documentation] for technical details.

== License

We have published these guidelines under the CC-BY (Creative commons
Attribution 4.0) license. Please see link:LICENSE[LICENSE file].
